//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int idCliente { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string rfc { get; set; }
        public string direccionFiscal { get; set; }
        public string condicionesDePago { get; set; }
        public string observaciones { get; set; }
        public int idVendedor { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime ultimaVisita { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
