//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int idContacto { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string empresa { get; set; }
        public string direccion { get; set; }
        public string observaciones { get; set; }
        public string valoracion { get; set; }
        public string cotizacion { get; set; }
        public int idVendedor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
